### ISSUE TITLE
Folders are missing if you login from another device

### ISSUE THREAD

**Issue by andys448** [mrFreeman-G/rocketchat-telegram-theme#1]
Description:
Hi. First of all - thanks for this theme and your features for Rocket.Chat. This awesome:)

If you login from another device your folders disappear.

Steps to reproduce:
Go to 'Electron app' / 'Create Folder' /// 'Go to web version / Folders disappear'

Expected behavior:
All your previously created folders are available

Do you have plans for implement on server side this feature that all folders saving for all users?

Server Setup Information:
Version of Rocket.Chat Server: 6.3.11
Operating System: RHEL 8
Deployment Method: Docker
Number of Running Instances: 20
DB Replicaset Oplog: Enabled
NodeJS Version: 14.21.2
MongoDB Version: 5.0.15 / wiredTiger
Client Setup Information
Desktop App or Browser Version: Electron App, Chrome Browser (64-bit)
Operating System: Windows 11
![image](https://github.com/mrFreeman-G/rocketchat-telegram-theme/assets/78227059/34aede12-59e9-4a32-b018-16b88ee6324d)

**Comment by mrFreeman-G** [comment]
Greetings, Andrey!

Since there is no way to store external data, such as folders on server side, there is no way to sync it from app to app.
Folders is stored in LocalStorage of your brwoser/app, so you have to setup it again on new device.

BTW, I have plans to make export/import folders and settings feature in future releases :)

**Comment by mrFreeman-G** [comment]
Hey @andys448, i've added Export/Import feature in [v0.5.0](https://github.com/mrFreeman-G/rocketchat-telegram-theme/releases/tag/v0.5.0)
